#!/bin/sh -e
AOC_YEAR=2015
AOC_DAYS=01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17
AOC_VARIANTS=gcc,tcc,cproc,clang
AOC_VARIANT=gcc
AOC_BUILD=aoc_build
aoc_build() {
    case "${AOC_VARIANT}" in
        gcc)   make CC="gcc"   CFLAGS="-O3 -std=c99" clean all;;
        tcc)   make CC="tcc"   CFLAGS=""             clean all;;
        cproc) make CC="cproc" CFLAGS=""             clean all;;
        clang) make CC="clang" CFLAGS="-O3 -std=c99" clean all;;
    esac
}
aoc_run() {
    ${AOC_RUNNER:-env} "${BUILDDIR:-./.build}/${1}"
}
